# Generated by Django 4.2.7 on 2023-11-17 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='country',
            new_name='state',
        ),
    ]
