# Generated by Django 4.2.7 on 2024-01-24 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_discountstatuscode_product_discount_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_status_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.discountstatuscode'),
        ),
    ]
